version: '3.8'

services:
        backend:
                image: backend
                ports:
                        - 8080:8080
                container_name: app-backend
                build: example-backend/
                depends_on:
                        - postgres-db
                command: ["./server"]
        frontend:
                image: frontend
                ports:
                        - 5000:5000
                container_name: app-frontend
                build: example-frontend/
                command: ["serve", "-s", "-l", "5000", "build"]
        redis-db:
                image: redis
                ports: 
                        - 6379:6379
        postgres-db:
                image: postgres:13.2-alpine
                restart: unless-stopped
                ports:
                        - 5432:5432
                environment:
                        POSTGRES_PASSWORD: postgres
                volumes:
                        - type: bind
                          source: ./database
                          target: /var/lib/postgresql/data
volumes:
        database: 
